# Better Documentation
# Manual for Students
# Brush-Up C Concepts (Questions about Pointers)
# Virtual Memory + Copy-On-Write

[env]
KERNEL_FILES = """
kernel/src/boot/linker.ld
build/entry.o
build/long.o
build/kernel.a
"""
BOOTLOADER_FILES = """
bootloader/src/linker.ld
build/boot.o
build/bootloader.a
"""
DEBUG_MODE = "console"

# Ensure everything is in place and clear build folder
[tasks.clean]
clear = true
script = [
    "mkdir -p build",
    "rm -rf ./build/*",
]

# Build Bootloader
[tasks.build_bootloader]
dependencies = ["clean"]
workspace = false
script = [
    "export KERNEL_SECTORS=$(./scripts/get_size.sh)",
    "cd bootloader",
    
    # Compile Bootloader binaries
    "nasm -dKERNEL_SIZE=$KERNEL_SECTORS -f elf64 src/boot.asm -o ../build/boot.elf",
    
    # Set ELF at origin address
    "ld -e _start_16 -Ttext=0x7C00 --oformat binary -o ../build/boot.bin ../build/boot.elf",
    "ld -e _start_16 -Ttext=0x7C00 --oformat elf64-x86-64 -o ../build/bootloader.elf ../build/boot.elf",
    "rm ../build/boot.elf",
    "objdump -S ../build/bootloader.elf > ../build/boot.asm",
]

# Build Kernel
[tasks.build_kernel]
dependencies = ["clean"]
workspace = false
script = [
    "cd kernel",

    # Compile Kernel and move to build Kernel
    "nasm -f elf64 src/boot/entry.asm -o ../build/entry.o",
    "nasm -f elf64 src/boot/long.asm -o ../build/long.o",
    "cargo build --target x86_64-target.json --features ${DEBUG_MODE}",
    "cd ..",
    "cp target/x86_64-target/debug/libbuzz_os_kernel.a build/kernel.a",
    
    # Link Kernel binaries
    "ld -n -o build/kernel.elf -T ${KERNEL_FILES}",
    "objcopy -O binary build/kernel.elf build/kernel.bin",
    "objdump -S -j .text.entry build/kernel.elf > build/kernel.asm",
    "rm build/long.o build/kernel.a build/entry.o"
]

# Build bootloader asm files
[tasks.build_run]
dependencies = ["build_kernel", "build_bootloader"]
workspace = false
script = [
    # Generate disk image
    "dd if=/dev/zero of=build/buzz.img count=10000 status=none",
    "dd if=build/boot.bin of=build/buzz.img conv=notrunc status=none",
    "dd if=build/kernel.bin of=build/buzz.img seek=1 conv=notrunc status=none",
    "rm build/kernel.bin",
    "rm build/boot.bin",
    
    # Start OS
    "scripts/build.sh",
]

[tasks.default]
alias = "build_run"