[env]
USER_PROGRAMS = """
user/init
user/test
"""
KERNEL_FILES = """
entry.o
switch.o
kernel.o
trap.o
"""
BOOTLOADER_FILES = """
bootloader/src/linker.ld
build/boot.o
build/bootloader.a
"""

# Ensure everything is in place and clear build folder
[tasks.clean]
clear = true
script = [
    "mkdir -p build",
    "rm -rf ./build/*",
]

# Build Bootloader
[tasks.build_bootloader]
dependencies = ["clean"]
workspace = false
script = [
    "cd bootloader",
    
    # Compile Bootloader binaries
    "nasm -f elf32 src/boot.asm -o ../build/boot.elf",
    
    # Set ELF at origin address
    "x86_64-elf-ld -m elf_i386 -e _start_16 -Ttext=0x7C00 --oformat binary -o ../build/boot.bin ../build/boot.elf",
    "x86_64-elf-ld -m elf_i386 -e _start_16 -Ttext=0x7C00 --oformat elf32-i386 -o ../build/bootloader.elf ../build/boot.elf",
    "objdump -S ../build/bootloader.elf > ../build/boot.asm",
    "objdump -S ../build/kernel.elf > ../build/kernel.asm",
    "rm ../build/boot.elf",
]

[tasks.build_user]
dependencies = ["clean"]
workspace = false
script = [
    "cd user",
    "cargo build",

    "cd ../build",
    "mkdir user",
    "find ../user/target/x86-target/debug/ ! -name \"*.*\" -type f -maxdepth 1 -exec cp {} ./user ';'",
]
  
[tasks.build_mkfs]
dependencies = ["clean"]
workspace = false
script = [    
  "cd mkfs",    
  "cargo build",    
  "cd ../build",
  "cp ../mkfs/target/debug/mkfs ./",
]

[tasks.create_fs]
dependencies = ["build_mkfs", "build_user"]
workspace = false
script = [
    "cd build",
    "./mkfs fs.img $USER_PROGRAMS",
    # "./mkfs fs.img",
    "cd ..",
]

# Build Kernel
[tasks.build_kernel]
dependencies = ["clean"]
workspace = false
script = [
    "cd kernel",

    # Compile Kernel and move to build Kernel
    "nasm -f elf32 src/boot/entry.asm -o ../build/entry.o",
    "nasm -f elf32 src/asm/switch.asm -o ../build/switch.o",
    "nasm -f elf32 src/asm/trap.asm -o ../build/trap.o",
    "nasm -f bin src/asm/init.asm -o ../build/init",

    "RUSTFLAGS=-g cargo build --target x86-target.json",
    "cd ..; cp target/x86-target/debug/libbuzz_os_kernel.a build/kernel.o",
    
    # Link Kernel binaries
    "cd build",
    "x86_64-elf-ld -m elf_i386 -n -o kernel.elf -T ../kernel/src/boot/linker.ld entry.o switch.o kernel.o trap.o --oformat elf32-i386 -b binary init",
    "rm kernel.o entry.o switch.o trap.o init"
  
    # # ORIGINAL MAKEFILE: DOES NOT WORK WITH M1
    # "cd build",
    # "ld -n -T ../kernel/src/boot/linker.ld -o kernel.elf ${KERNEL_FILES} -b binary init",
    # "rm kernel.o entry.o"
]

# Build and run
[tasks.build_run]
dependencies = ["build_kernel", "build_bootloader", "create_fs"]
workspace = false
script = [
    # Generate kernel disk image
    "dd if=/dev/zero of=build/buzz.img count=10000 status=none",
    "dd if=build/boot.bin of=build/buzz.img conv=notrunc status=none",
    "dd if=build/kernel.elf of=build/buzz.img seek=1 conv=notrunc status=none",
    "rm build/boot.bin",
    
    # Start OS
    "qemu-system-i386 -nographic -drive file=build/buzz.img,index=0,media=disk,format=raw -drive file=build/fs.img,index=1,media=disk,format=raw -no-shutdown -no-reboot -m 512",
]

# Build and run with GDB
[tasks.gdb]
dependencies = ["build_kernel", "build_bootloader"]
workspace = false
script = [
    # Generate disk image
    "dd if=/dev/zero of=build/buzz.img count=10000 status=none",
    "dd if=build/boot.bin of=build/buzz.img conv=notrunc status=none",
    "dd if=build/kernel.elf of=build/buzz.img seek=1 conv=notrunc status=none",
    "rm build/boot.bin",
    
    # Start OS with GDB
    "qemu-system-i386 -s -S -drive file=build/buzz.img,index=0,media=disk,format=raw -drive file=build/fs.img,index=1,media=disk,format=raw -no-reboot -no-shutdown -nographic -serial mon:stdio -m 512",
]

[tasks.default]
alias = "build_run"
