[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[build]
rustflags = ["--emit", "asm", "-C", "llvm-args=-x86-asm-syntax=intel", "-C", "save-temps", "--emit=llvm-ir"]
target = "i686-unknown-none.json"