[package]
name = "mkfs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[package.metadata]
cargo-features = ["build-std"]

[dependencies]
endian_codec = "0.1.1"
shared_fs = {path = "../shared_fs/"}
